version: '3.8'

services:
  # db:
  #   image: postgres:15-alpine
  #   restart: always
  #   environment:
  #     POSTGRES_DB: sportsocial
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

  app:
    build: .
    # depends_on:
    #   - db
    ports:
      - "8080:8080"
    restart: always
    command: ["java", "-jar", "app.jar"]
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/sportsocial
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  pgdata: 